### ISSUE TITLE
Files do not show up in preview

### ISSUE THREAD

**Issue by ArtemisFowl-san** [OlegLustenko/obsidian-bulk-rename#15]
I tried using the plug in to rename quite a few files from the root folder in Obsidian (/) and the files do not show up in preview when I click on it and I therefore can't rename them. When I try it on a really small folder, the files show up, so maybe it's simply the number of files in the root folder ~ 2500. I have waited for around a minute before without anything happening, is this normal? I'm using the Insider version 16.03 if that makes a difference.

**Comment by OlegLustenko** [comment]
Hi @ArtemisFowl-san, it's sounds like a bug.

Could you please try delete `/`? 

it should select everything from root.

I would add some indicator if there is any loading happening.

I've tried at vault with 1500 items and it took less than 2 seconds, almost immediately.

I'll have a look at it soon

**Comment by OlegLustenko** [comment]
Landed in #16

Release is going to be happen soon

**Comment by OlegLustenko** [comment]
Landed!

https://github.com/OlegLustenko/obsidian-bulk-rename/releases/tag/0.4.1

If you still have any issues, please reach to me

**Comment by ArtemisFowl-san** [comment]
I updated and worked like a charm this time. Thank you for the quick turnaround!
