### ISSUE TITLE
Preview shows only a limited number of results

### ISSUE THREAD

**Issue by rlolingo** [OlegLustenko/obsidian-bulk-rename#17]
Hi there, thanks for a great plugin!

Though i'm having trouble seeing the preivew, its showing only a limited number of results.
Im only seeing 3-4 preview results at most.

I thought it was my CSS Modifications causing it at first, but the issue seems to persist despite creating a new vault.

![image](https://user-images.githubusercontent.com/34475976/192162425-ba886ec5-1b45-4508-bd25-6543e68e2161.png)

**Comment by OlegLustenko** [comment]
Hi @rlolingo , thank you for the feedback!
I checked with the default theme, and looks not so pretty.
I'll improve it

**Comment by OlegLustenko** [comment]
Resolved with #18 
Shipped with latest version!

Thank you for pointing it

**Comment by OlegLustenko** [comment]
Closed as complete
