### ISSUE TITLE
Add ability to using regex capturing groups

### ISSUE THREAD

**Issue by tonyxiao** [OlegLustenko/obsidian-bulk-rename#20]
I'd like to rename 20210101 to 2021-01-01 and this does not appear to be possible :(

**Comment by tonyxiao** [comment]
@OlegLustenko I think it's a one line change

https://github.com/OlegLustenko/obsidian-bulk-rename/blob/master/src/services/file.service.ts#L59

All it takes is not escaping regex. Let me know if you are ok with a PR for that.

**Comment by tonyxiao** [comment]
<img width="854" alt="CleanShot 2022-11-01 at 17 50 27@2x" src="https://user-images.githubusercontent.com/696842/199290250-a4e82554-0599-4d4d-98e8-d04794020cb1.png">
Then powerful use cases like this can be enabled

**Comment by OlegLustenko** [comment]
Hi, thank you for your attention to the plugin!

Definitely, if you know what to do and where to do it, go for it!

Ideally, if we'll cover such a case with a test case

**Comment by OlegLustenko** [comment]
In general, I'm thinking about providing more powerful/easier ways to work with RegExp.

So it will be more user-friendly for the cases you mentioned without requiring advanced knowledge about Regular Expressions

And I've tried `XRegExp.escape(str)` but it didn't pass existing tests. Didn't have a chance to figure out if there is an issue with existing tests or if it's related to how XRegExp is dealing with escape

**Comment by tonyxiao** [comment]
Hmm this is what I changed and I was able to get it working locally. 

I think to start off it can be as simple as single checkbox to say regex or not for the `Existing` field. That way we make the advanced possible while keeping the simple simple. What do you think?

<img width="489" alt="image" src="https://user-images.githubusercontent.com/696842/199298749-82dab0eb-7867-4b52-866f-0de5658b48d5.png">

**Comment by OlegLustenko** [comment]
Sounds perfect! Thanks for your feedback and contributions 

Feel free to create a PR about it.

**Comment by tonyxiao** [comment]
Awesome. Not familiar with how obsidian plugins work so might take me some time to figure out how to add the checkbox (if anything special). Otherwise just a trivial one line change though :)

**Comment by cvh-obsi** [comment]
very interested to have this feature

**Comment by OlegLustenko** [comment]
I can work on it, I answered here https://github.com/OlegLustenko/obsidian-bulk-rename/issues/22#issuecomment-1413625569

More real-world examples will be beneficial!

cc: @tonyxiao @cvh-obsi

**Comment by cvh-obsi** [comment]
> I can work on it, I answered here [#22 (comment)](https://github.com/OlegLustenko/obsidian-bulk-rename/issues/22#issuecomment-1413625569)
> 
> More real-world examples will be beneficial!
> 
> cc: @tonyxiao @cvh-obsi

what tonyxiao describes here is exactly what I need: https://github.com/OlegLustenko/obsidian-bulk-rename/issues/20#issuecomment-1298823810

**Comment by cvh-obsi** [comment]
another example: my notes filename begin with a code like this : 10c2 (a number with 1 or 2 digits, an char (a to z), 1/2 digits and I want to add a period between alpha and numerics, and also add a  0(zero) in front of numbers with only 1 digit

**Comment by OlegLustenko** [comment]
Solved in the scope of https://github.com/OlegLustenko/obsidian-bulk-rename/pull/23

Feedback is welcome!

Released with the 0.5.2 version

Thanks, everyone, for your contribution
cc: @cvh-obsi, @Chriswaterguy @tonyxiao

**Comment by OlegLustenko** [comment]
Closing as implemented

**Comment by tonyxiao** [comment]
amazing! Thank you @OlegLustenko
