### ISSUE TITLE
Regex doesn't match and replace groups. 

### ISSUE THREAD

**Issue by Chriswaterguy** [OlegLustenko/obsidian-bulk-rename#22]
I've tried matching groups, so that I can change the order of characters in my titles. E.g. if I want to move FOO from the start to the end, I might do
Existing: FOO(.+)
Replacement: $1FOO

But the preview shows no change. 

I have also tried with \1 and \\1 instead of $1.

**Comment by cvh-obsi** [comment]
see this thread (same request): https://github.com/OlegLustenko/obsidian-bulk-rename/issues/20

**Comment by OlegLustenko** [comment]
Well, I can work on it, Could you help me to add some specific cases so I can verify the results?

Since existing libraries have a different implementation of RegExp

cc: @cvh-obsi, @Chriswaterguy 

Ideally, results will include -> Existing, Replacement

**Comment by Chriswaterguy** [comment]
> Since existing libraries have a different implementation of RegExp

Could we have exactly the same flavour as the Obsidian search function? That would minimise confusion.

**Comment by OlegLustenko** [comment]
So, Status update:

- RegExp is not currently supported in **Existing** or **Replacement**, only strings can be pasted here.

However, I'm working on making it work there too

**Comment by OlegLustenko** [comment]
Ok, I made it work going to release it today or tomorrow!

Thanks everyone for feedback

**Comment by OlegLustenko** [comment]
Solved in the scope of https://github.com/OlegLustenko/obsidian-bulk-rename/pull/23

Feedback is welcome!

Released with 0.5.2 version

Thanks, everyone for contribution
cc: @cvh-obsi, @Chriswaterguy

**Comment by OlegLustenko** [comment]
Closing as implemented
